import { PhoneEntry } from './types';

export const INITIAL_PHONE_DATA: PhoneEntry[] = [
  // อาคาร 100 ปี
  { id: '1', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'เวชระเบียน 100 ปี', number: '1066' },
  { id: '2', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์เปล ER', number: '1129' },
  { id: '3', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องจ่ายยาผู้ป่วยใน #50', number: '1012' },
  { id: '4', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องจ่ายยานอกเวลา เบอร์ 7', number: '1072' },
  { id: '5', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องการเงินผู้ป่วยนอก เบอร์ 6', number: '1017' },
  { id: '6', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์สั่งการอุบัติเหตุ', number: '1067' },
  { id: '7', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องคิดเงินผู้ป่วยใน #51', number: '1102' },
  { id: '8', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์จำหน่ายผู้ป่วย # 52', number: '1084' },
  { id: '9', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องทำแผล', number: '1071' },
  { id: '10', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์ X-Ray Computer (CT สแกน)', number: '1075' },
  { id: '11', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้อง X-Ray/หัวหน้า', number: '1070 / 2005' },
  { id: '12', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องพักเวร X-Ray', number: '1069 / 2006' },
  { id: '13', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องอัลตราซาวด์ (พ.นภาพร)', number: '1068' },
  { id: '14', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องอัลตราซาวด์ (พ.อรอุมา)', number: '1076' },
  { id: '15', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'คลังยา', number: '1118' },
  { id: '16', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องหัวหน้างานอุบัติเหตุ', number: '1073' },
  { id: '17', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องฉุกเฉิน', number: '1074 / 1108 / 1058' },
  { id: '18', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'จุดซักประวัติ ER', number: '1086' },
  { id: '19', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์ Refer', number: '1164' },
  { id: '20', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องส่องกล้องลำไส้', number: '1176' },
  { id: '21', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องผ่าตัด', number: '1126 / 1127' },
  { id: '22', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'วิสัญญี', number: '1128 / 1183' },
  { id: '23', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องพักเวรพยาบาลผ่าตัด/วิสัญญี', number: '1226' },
  { id: '24', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'OR ซับพลาย', number: '2010' },
  { id: '25', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'OR ตา', number: '1103' },
  { id: '26', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วย NICU', number: '1063 / 2008' },
  { id: '27', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผุ้ป่วย MICU', number: '1135 / 1136' },
  { id: '28', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วย SICU ชั้น 3', number: '1047 / 2007' },
  { id: '29', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วยศัลยกรรมชาย', number: '1091 / 2019' },
  { id: '30', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วยศัลยกรรมหญิง', number: '1094 / 2020' },
  { id: '31', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วย ICU ชั้น 5', number: '1096' },
  { id: '32', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วยศัลยกรรมกระดูก', number: '1107' },
  { id: '33', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วยพิเศษ ชั้น 6', number: '1020 / 2021' },
  { id: '34', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'หอผู้ป่วยพิเศษ ชั้น 7', number: '1069 / 2022' },
  { id: '35', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องประชุมพระราม 9 (ห้องให้คีโม) ชั้น 7', number: '1172' },
  { id: '36', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'MRI (091-4210258)', number: '1188' },
  { id: '37', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์สลายนิ่ว', number: '1184' },
  { id: '38', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ศูนย์ซ่อมอุปกรณ์การแพทย์ อาคารจ่ายกลาง', number: '1159' },
  { id: '39', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องปราศจากเชื้อ (พี่ไผ่คลังผลิต)', number: '1116' },
  { id: '40', building: 'อาคาร 100 ปี สมเด็จพระญาณสังวร', department: 'ห้องผ่าตัดเล็ก', number: 'ห้อง 1-8 (2011-2018)' },

  // อาคารผู้ป่วยนอก OPD
  { id: '41', building: 'อาคารผู้ป่วยนอก OPD', department: 'ประชาสัมพันธ์ (ในเวลาราชการ)', number: '0 / 1000 / 1001' },
  { id: '42', building: 'อาคารผู้ป่วยนอก OPD', department: 'ประชาสัมพันธ์ (นอกเวลาราชการ)', number: '0 / 2999' },
  { id: '43', building: 'อาคารผู้ป่วยนอก OPD', department: 'เวชระเบียนผู้ป่วยนอก', number: '1048 / 1002' },
  { id: '44', building: 'อาคารผู้ป่วยนอก OPD', department: 'ศูนย์เปล', number: '1144' },
  { id: '45', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องหัวหน้า OPD (ชั้น 1)', number: '1005' },
  { id: '46', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องจ่ายยาผู้ป่วยนอก', number: '1014 / 1121' },
  { id: '47', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องคิดเงินผู้ป่วยนอก', number: '1018' },
  { id: '48', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้อง LAB OPD (ชั้น 1)', number: '1021' },
  { id: '49', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องฉีดยา', number: '1026' },
  { id: '50', building: 'อาคารผู้ป่วยนอก OPD', department: 'กายภาพบำบัด', number: '1149 / 1158' },
  { id: '51', building: 'อาคารผู้ป่วยนอก OPD', department: 'กิจกรรมบำบัด', number: '1148' },
  { id: '52', building: 'อาคารผู้ป่วยนอก OPD', department: 'เวชระเบียนผู้ป่วยใน', number: '1033' },
  { id: '53', building: 'อาคารผู้ป่วยนอก OPD', department: 'จองห้องพิเศษ (8.00-12.00)', number: '1120' },
  { id: '54', building: 'อาคารผู้ป่วยนอก OPD', department: 'ศูนย์ Admit นอน รพ.', number: '1120' },
  { id: '55', building: 'อาคารผู้ป่วยนอก OPD', department: 'ศูนย์วัสดุการแพทย์ # 15', number: '1114' },
  { id: '56', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องทำงานเภสัช', number: '1115' },
  { id: '57', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องตรวจสอบสิทธิ #5', number: '1061 / 1062' },
  { id: '58', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องเภสัชกรรม (คุณสิทธิ)', number: '1119' },
  { id: '59', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกอายุรกรรม', number: '1034 / 1035' },
  { id: '60', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องจ่ายยาผู้ป่วยนอก ชั้น 2', number: '1117' },
  { id: '61', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องการเงินผู้ป่วยนอก ชั้น 2', number: '1113' },
  { id: '62', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกศัลยกรรมกระดูก', number: '1011' },
  { id: '63', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกนรีเวชกรรม / ANC', number: '1022 / 1024' },
  { id: '64', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกศัลยกรรม', number: '1132 / 1006' },
  { id: '65', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกศัลยกรรมทางเดินปัสสาวะ', number: '1132 / 1006' },
  { id: '66', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกเวชศาสตร์ฟื้นฟู', number: '1008' },
  { id: '67', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกกัญชา+คลินิกประคับประคอง', number: '1016' },
  { id: '68', building: 'อาคารผู้ป่วยนอก OPD', department: 'ศูนย์คลินิกนอกเวลา SMC (พี่มิ้ม)', number: '1161' },
  { id: '69', building: 'อาคารผู้ป่วยนอก OPD', department: 'จุดคัดกรอง OPD', number: '1173' },
  { id: '70', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องดีแพค', number: '1150' },
  { id: '71', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องหัวหน้า OPD ตา', number: '1009' },
  { id: '72', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องตรวจตา', number: '1010' },
  { id: '73', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกจิตเวช / คลินิกใกล้ใจ', number: '1027 / 1015' },
  { id: '74', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิก หู คอ จมูก ENT', number: '1036' },
  { id: '75', building: 'อาคารผู้ป่วยนอก OPD', department: 'คลินิกกุมารเวช', number: '1130' },
  { id: '76', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานอาชีวเวชกรรม', number: '1087' },
  { id: '77', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องพี่ยุ้ย ออร์ดิจชาร์ต', number: '1155' },
  { id: '78', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานทันตกรรม', number: '1028 / 1029 / 1030' },
  { id: '79', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานเคมีวิทยา', number: '1080' },
  { id: '80', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานโลหิตวิทยา (LAB)', number: '1079' },
  { id: '81', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานจุลชีววิทยา (แบคทีเลีย)', number: '1081' },
  { id: '82', building: 'อาคารผู้ป่วยนอก OPD', department: 'ธนาคารเลือด', number: '1082' },
  { id: '83', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานภูมิคุ้มกัน', number: '1083' },
  { id: '84', building: 'อาคารผู้ป่วยนอก OPD', department: 'เซลล์วิทยา (ส่งชิ้นเนื้อ)', number: '1171' },
  { id: '85', building: 'อาคารผู้ป่วยนอก OPD', department: 'องค์กรแพทย์ (ห้องพักแพทย์)', number: '1077 , 1078' },
  { id: '86', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องรอง ผอ.ฝ่ายการแพทย์', number: '2001' },
  { id: '87', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องรอง ผอ.ฝ่ายบริหาร', number: '2002' },
  { id: '88', building: 'อาคารผู้ป่วยนอก OPD', department: 'กลุ่มงานบริหารทั่วไป', number: '1043' },
  { id: '89', building: 'อาคารผู้ป่วยนอก OPD', department: 'หน้าห้องท่านผู้อำนวยการ', number: '2000' },
  { id: '90', building: 'อาคารผู้ป่วยนอก OPD', department: 'งานธุรการ', number: '1045' },
  { id: '91', building: 'อาคารผู้ป่วยนอก OPD', department: 'การเงิน', number: '1044 / 1143' },
  { id: '92', building: 'อาคารผู้ป่วยนอก OPD', department: 'ฝ่ายการเจ้าหน้าที่', number: '1040' },
  { id: '93', building: 'อาคารผู้ป่วยนอก OPD', department: 'กลุ่มงานพัสดุ', number: '1046' },
  { id: '94', building: 'อาคารผู้ป่วยนอก OPD', department: 'ศูนย์คุณภาพ (HA)', number: '1056' },
  { id: '95', building: 'อาคารผู้ป่วยนอก OPD', department: 'ศูนย์ข้อมูล', number: '1187' },
  { id: '96', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องนิติกร', number: '1064' },
  { id: '97', building: 'อาคารผู้ป่วยนอก OPD', department: 'หัวหน้ากลุ่มการพยาบาล', number: '1125' },
  { id: '98', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องกลุ่มการพยาบาล', number: '1050 / 1054' },
  { id: '99', building: 'อาคารผู้ป่วยนอก OPD', department: 'กลุ่มงานประกันสุขภาพ', number: '1088' },
  { id: '100', building: 'อาคารผู้ป่วยนอก OPD', department: 'บัญชี', number: '1145' },
  { id: '101', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องโสตทัศนูปกรณ์', number: '1055' },
  { id: '102', building: 'อาคารผู้ป่วยนอก OPD', department: 'เทคโนโลยีสารสนเทศ', number: '1037' },
  { id: '148', building: 'อาคารผู้ป่วยนอก OPD', department: 'Hardware', number: '2031' },
  { id: '149', building: 'อาคารผู้ป่วยนอก OPD', department: 'ดิจิทัล', number: '2032' },
  { id: '150', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องพี่ต่อ หัวหน้า', number: '1170' },
  { id: '103', building: 'อาคารผู้ป่วยนอก OPD', department: 'กลุ่มงานวิชาการ', number: '1052' },
  { id: '104', building: 'อาคารผู้ป่วยนอก OPD', department: 'ห้องหมอธนันชัย', number: '1060' },

  // อาคารรวมน้ำใจ
  { id: '105', building: 'อาคารรวมน้ำใจ', department: 'ห้องจ่ายเวชภัณฑ์', number: '1098' },
  { id: '106', building: 'อาคารรวมน้ำใจ', department: 'หอผู้ป่วยอายุรกรรมหญิง', number: '1092 / 1089' },
  { id: '107', building: 'อาคารรวมน้ำใจ', department: 'หอผู้ป่วยตา หู คอ จมูก', number: '1111' },
  { id: '108', building: 'อาคารรวมน้ำใจ', department: 'ห้องมูลนิธิ (ห้องบริจาค)', number: '1138' },
  { id: '109', building: 'อาคารรวมน้ำใจ', department: 'หอผู้ป่วยสุขใจ', number: '1090' },

  // อาคารเฉลิมพระเกียรติ
  { id: '110', building: 'อาคารเฉลิมพระเกียรติ', department: 'คลินิก TB / ARI', number: '1100 / 1101' },
  { id: '111', building: 'อาคารเฉลิมพระเกียรติ', department: 'ห้องสังคมสงเคราะห์', number: '1031' },
  { id: '112', building: 'อาคารเฉลิมพระเกียรติ', department: 'ห้องคลอด', number: '1104' },
  { id: '113', building: 'อาคารเฉลิมพระเกียรติ', department: 'ห้องอบอุณหภูมิเด็ก', number: '1105' },
  { id: '114', building: 'อาคารเฉลิมพระเกียรติ', department: 'หอผู้ป่วยจิตเวช', number: '1095' },
  { id: '115', building: 'อาคารเฉลิมพระเกียรติ', department: 'หอผู้ป่วยสูติ-นรีเวชกรรม', number: '1106' },
  { id: '116', building: 'อาคารเฉลิมพระเกียรติ', department: 'งาน IC', number: '1112' },
  { id: '117', building: 'อาคารเฉลิมพระเกียรติ', department: 'หอผู้ป่วยอายุรกรรมชาย', number: '1093 / 1097' },
  { id: '118', building: 'อาคารเฉลิมพระเกียรติ', department: 'หอผู้ป่วยกุมารเวชกรรม', number: '1109 / 1110' },

  // อาคารแผนไทย
  { id: '119', building: 'อาคารแผนไทย', department: 'ศูนย์ประสานงาน (ศูนย์เยี่ยมบ้าน)', number: '1065 / 1053' },
  { id: '120', building: 'อาคารแผนไทย', department: 'ห้องนวดแผนไทย', number: '1085' },

  // อาคารศูนย์แพทย์
  { id: '121', building: 'อาคารศูนย์แพทย์', department: 'ห้องสมุด ศูนย์แพทย์', number: '3000 ต่อ 1034' },
  { id: '122', building: 'อาคารศูนย์แพทย์', department: 'ศูนย์แพทย์', number: '3000' },

  // หน่วยงานต่างๆนอกอาคาร
  { id: '123', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'ศูนย์ตรวจสุขภาพมวลกระดูก', number: '2003' },
  { id: '124', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'กลุ่มงานเวชกรรมสังคม', number: '1051 / 1245' },
  { id: '125', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'คลังพัสดุ', number: '1142' },
  { id: '126', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'หัวหน้าโภชนาการ', number: '1146' },
  { id: '127', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'โรงครัว', number: '1147' },
  { id: '128', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'งานซักฟอก/หัวหน้า', number: '1023 / 2004' },
  { id: '129', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'งานนิติเวช', number: '1179' },
  { id: '130', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'ห้องนึ่งของ', number: '1139' },
  { id: '131', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'งานศูนย์จ่ายกลาง', number: '1140 / 2009' },
  { id: '132', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'โลจิสติกส์ (พี่ปุ้ม)', number: '1166' },
  { id: '133', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'โรงพักศพ', number: '1151' },
  { id: '134', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'งานซ่อมบำรุง / บำบัดน้ำเสีย', number: '1152' },
  { id: '135', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'งานอาคารสถานที่', number: '1153' },
  { id: '136', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'โรงรถ', number: '1154' },
  { id: '137', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'โรงพักขยะ', number: '1182' },
  { id: '138', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'ห้องตรวจสุขภาพต่างด้าว', number: '1003' },
  { id: '139', building: 'หน่วยงานต่างๆนอกอาคาร', department: 'กายอุปกรณ์', number: '1181' },

  // อาคาร 75 ปี ตึกเขียว
  { id: '140', building: 'อาคาร 75 ปี ตึกเขียว', department: 'อุปกรณ์การแพทย์ (ศูนย์เวน)', number: '1163' },
  { id: '141', building: 'อาคาร 75 ปี ตึกเขียว', department: 'ห้อง Eco หัวใจ', number: '1059' },
  { id: '142', building: 'อาคาร 75 ปี ตึกเขียว', department: 'ไตเทียม', number: '1134 / 1032' },
  { id: '143', building: 'อาคาร 75 ปี ตึกเขียว', department: 'ไตเทียมเอกชน', number: '1038' },
  { id: '144', building: 'อาคาร 75 ปี ตึกเขียว', department: 'ห้องล้างไตหน้าท้อง', number: '1041' },
  { id: '145', building: 'อาคาร 75 ปี ตึกเขียว', department: 'ห้องพิเศษอายุรกรรม ชั้น 2', number: '1049' },
  { id: '146', building: 'อาคาร 75 ปี ตึกเขียว', department: 'ห้องพิเศษอายุรกรรม ชั้น 4', number: '1099' },
  { id: '147', building: 'อาคาร 75 ปี ตึกเขียว', department: 'หอผู้ป่วย พระสงซ์ ชั้น 6', number: '1004' }
];